version: '3'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
        - "8080:8080"
    depends_on: 
      - app
    networks:
      - node-network


  app:
    build:
      context: node
    networks:
      - node-network
    volumes:
      -  ./node:/usr/src/app
    tty: true
    container_name: app  
    ports:
       - "3000:3000"
    depends_on: 
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true   
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root     
    networks:
      - node-network

networks:
  node-network:
    driver: bridge